import StyledComponentsRegistry from '@/lib/registry'
import Globals from '@/styles/Globals'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'mt.dev - strony internetowe',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pl">
      <body id="main">
        <Globals />
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  )
}
